apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-order
  namespace: notifications-s19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-order
  template:
    metadata:
      labels:
        app: postgres-order
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "orderdb"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "user", "-d", "orderdb"]
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-order
  namespace: notifications-s19
spec:
  selector:
    app: postgres-order
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
